# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-22 16:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0002_auto_20180222_2131'),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('price', models.IntegerField()),
                ('status', models.CharField(max_length=100)),
                ('prev_id', models.IntegerField(blank=True, null=True)),
                ('prev_hash', models.BinaryField(blank=True, null=True)),
                ('buyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buyer', to='blockchain.Shopper')),
                ('seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seller', to='blockchain.Shopper')),
            ],
        ),
    ]
