# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-24 05:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0003_block'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='block',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
