# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-24 14:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0004_auto_20180224_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopper',
            name='public_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
